# Generated by Django 4.0 on 2021-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0003_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(max_length=500)),
                ('spi', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='forecast',
            name='city',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='tmef',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='tmn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='tmx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='wf',
            field=models.TextField(null=True),
        ),
    ]
